services:
  - type: web
    name: viddown-server
    env: node
    plan: free
    buildCommand: "cd server && chmod +x install-yt-dlp.sh && ./install-yt-dlp.sh && npm install"
    startCommand: "cd server && node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
