services:
  - type: web
    name: viddown-server
    env: node
    plan: free
    buildCommand: "cd server && pip install yt-dlp && npm install"
    startCommand: "cd server && node server.js"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
